# fly.toml app configuration file generated for henkanflytesti on 2023-06-26T23:15:34+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "henkanflytesti"
primary_region = "arn"

[env]
  PORT = "8080" # lisätään tämä

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
